###############################################################################
# FILE: SD0083-TC2-Info.rq
# DESC: SD0083 RC2 : Missing USUBJID
#
# REQ : 
# SRC : 
# IN  : 
# OUT : 
# NOTE: 
# TODO: 
###############################################################################
PREFIX code:    <https://w3id.org/phuse/code#>
PREFIX cj16050: <https://example.org/cj16050#>
PREFIX cjprot: <https://example.org/cjprot#>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#> 
PREFIX study:   <https://w3id.org/phuse/study#> 
PREFIX time:    <http://www.w3.org/2006/time#>

SELECT ?animalIRI ?p ?o
WHERE{
  cj16050:Animal_69fa85ac ?p ?o .
   BIND(IRI(cj16050:Animal_6204e90c) AS ?animalIRI )
}