###############################################################################
# FILE: SD0083-TC1-Verify.rq
# DESC: USUBJID Rule Component 1 , Test Case 1 Verification
#
#
# REQ : 
# SRC : 
# IN  : 
# OUT : 
# NOTE: 
# TODO: 
###############################################################################

PREFIX cj16050: <https://example.org/cj16050#>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#> 
PREFIX study:   <https://w3id.org/phuse/study#> 

SELECT ?animalSubjectIRI (COUNT(?usubjidIRI) AS ?total) 
WHERE{
  ?animalSubjectIRI a                        study:AnimalSubject ;
                    study:hasUniqueSubjectID ?usubjidIRI .
  ?usubjidIRI       skos:prefLabel           ?usubjidLabel .
} GROUP BY ?animalSubjectIRI
  HAVING (?total != 1)
