###############################################################################
# FILE: USUBJID-RC1RC2-TC2-Info.rq
# DESC: USUBJID Rule Component 1,2 , Test Case 1 Information
#       Information based on report findings
#
# REQ : 
# SRC : 
# IN  : 
# OUT : 
# NOTE: 
# TODO: 
###############################################################################
PREFIX cj16050: <https://example.org/cj16050#>
PREFIX code:    <https://w3id.org/phuse/code#> 
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#> 
PREFIX study:   <https://w3id.org/phuse/study#> 
PREFIX time:    <http://www.w3.org/2006/time#>

SELECT ?animalIRI ?p ?o
WHERE{
  cj16050:Animal_22218ae1 ?p ?o .
   BIND(IRI(cj16050:Animal_6204e90c) AS ?animalIRI )
}