###############################################################################
# FILE: USUBJID-RC3-M1-Verify.rq
# DESC: USUBJID Rule Component 3, Method 1 (reference only) 
#
#
# REQ : 
# SRC : 
# IN  : 
# OUT : 
# NOTE: 
# TODO: 
###############################################################################

PREFIX cj16050: <https://example.org/cj16050#>
PREFIX code:    <https://w3id.org/phuse/code#> 
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#> 
PREFIX study:   <https://w3id.org/phuse/study#> 
PREFIX time:    <http://www.w3.org/2006/time#>

SELECT ?usubjidIRI (COUNT(?animalSubjectIRI) AS ?total) 
  WHERE{
    ?animalSubjectIRI a                        study:AnimalSubject ;
                      study:hasUniqueSubjectID ?usubjidIRI ;
                      skos:prefLabel           ?animalLabel .
    ?usubjidIRI       skos:prefLabel           ?usubjidLabel .
  } GROUP BY ?usubjidIRI
  HAVING (?total > 1)